# Configure main menu and social menu

#[[main]]
#identifier = "home"
#name = "首页"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/bingohuang"

[social.params]
icon = "brand-github"

[[social]]
identifier = "talks"
name = "Talks"
url = "http://talks.hibingo.cn/"

[social.params]
icon = "smile"
